version: '3'

services:
  scylla:
    image: scylladb/scylla
    container_name: scylla
    volumes:
      - scylla_data:/var/lib/scylla/data
    ports:
      - "9042:9042"
    restart: always

  demo:
    build: .
    image: scylladb/demo
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=scylla:9042
      - ROCKET_ADDRESS=0.0.0.0

volumes:
  scylla_data:
